name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set release env
        run: echo "release_version=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - name: Get modules
        run: go mod vendor
      - name: Test
        run: make test
      - name: Build
        run: make release
      - name: Package
        run: |
          rsync ./bin/pr-size-labeler-action_darwin_amd64 README.md LICENSE pr-size-labeler-action_darwin_amd64 && tar czvf pr-size-labeler-action_darwin_amd64.tar.gz pr-size-labeler-action_darwin_amd64
          rsync ./bin/pr-size-labeler-action_darwin_arm64 README.md LICENSE pr-size-labeler-action_darwin_arm64 && tar czvf pr-size-labeler-action_darwin_arm64.tar.gz pr-size-labeler-action_darwin_arm64
          rsync ./bin/pr-size-labeler-action_linux_amd64 README.md LICENSE pr-size-labeler-action_linux_amd64 && tar czvf pr-size-labeler-action_linux_amd64.tar.gz pr-size-labeler-action_linux_amd64
          rsync ./bin/pr-size-labeler-action_linux_arm64 README.md LICENSE pr-size-labeler-action_linux_arm64 && tar czvf pr-size-labeler-action_linux_arm64.tar.gz pr-size-labeler-action_linux_arm64
          rsync ./bin/pr-size-labeler-action_windows_amd64 README.md LICENSE pr-size-labeler-action_windows_amd64 && tar czvf pr-size-labeler-action_windows_amd64.tar.gz pr-size-labeler-action_windows_amd64
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            pr-size-labeler-action_darwin_amd64.tar.gz
            pr-size-labeler-action_darwin_arm64.tar.gz
            pr-size-labeler-action_linux_amd64.tar.gz
            pr-size-labeler-action_linux_arm64.tar.gz
            pr-size-labeler-action_windows_amd64.tar.gz

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: pr-size-labeler-action
          tags: latest v1
          containerfiles: |
            ./Containerfile

      - name: Push
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/cbrgm
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
